### ISSUE TITLE
Move from sleep statements to polling

### ISSUE THREAD

**Issue by jeremyf** [ndlib/QA_tests#100]
At present there are several sleep statements sprinkled throughout. I would like to encapsulate these sleeps into a single polling method.

Move from:
```ruby
sleep(5)
fill_in('passcode', passCode)
```

To something like:

```ruby
poll { fill_in('passcode', passCode) }
```

The poll method would try, wait, try again, wait longer, etc, until we hit the configured timeout. Once the timeout is hit, we'd fail the spec and mark what the failure was.

@h-parekh Thoughts?

**Comment by h-parekh** [comment]
Addressed in the [sleep injector logic](https://github.com/ndlib/QA_tests/blob/master/spec/spec_support/inject_sleep.rb)
