### ISSUE TITLE
Contentful specs for 'event' entry is using a hard coded libcal id

### ISSUE THREAD

**Issue by h-parekh** [ndlib/QA_tests#233]
Parameterize 'lib_cal_id' [argument](https://github.com/ndlib/QA_tests/blob/master/spec/contentful/integration/int_contentful_spec.rb#L31) as a variable from the ~/test_data/QA/parameters/contentful.yml file from shared drive.
We also need to be able to pick one random value from this list of libcalids to pass as an argument

Leverage the PathParameterizer::ParameterFinder class to build the dictionary and use its find method to pull values.

**Comment by mhallwac** [comment]
There is only one ID in contentful.yml file in the shared drive. Is this a precautionary fix so that when more libcalid(s) are added it is randomized?

**Comment by h-parekh** [comment]
Yes:
* Allows flexibility to add more values
* Builds consistency across the framework by keeping test data separate from code
* Helps avoid code changes (pull, push, merge cycle) when these values change

**Comment by h-parekh** [comment]
Fixed by https://github.com/ndlib/QA_tests/pull/242
