### ISSUE TITLE
Configure contentful handler to manage different contentful spaces

### ISSUE THREAD

**Issue by h-parekh** [ndlib/QA_tests#234]
We now have 2 contentful spaces to test the library website. However, the [ContentfulHandler.read_contentful_tokens](https://github.com/ndlib/QA_tests/blob/master/spec/spec_support/contentful_handler.rb#L65)
method reads only 'prod' tokens from the shared drive. 

- [X] Add the ability to pass a command line toggle USE_CONTENTFUL_SPACE (Similar to LOG_LEVEL, SKIP_CLOUDWATCH.. etc)
- [X] USE_CONTENTFUL_SPACE should only allow 'prep' and 'prod' as possible values, any other values should prompt an error and fail
- [X] Depending on the input value it should set the correct values in these variables
      @space_id
      @cdn_token
      @preview_token
      @personal_access_token
- [x] Update README to provide directions on how to use this toggle and what it does
- [x] Update bin/run_tests script to make allow using this toggle

**Comment by mhallwac** [comment]
Should the toggle default to prod if we are requiring it for contentful tests?

**Comment by h-parekh** [comment]
Yes, the idea is that the toggle would be used mostly in dev mode, and when the tests are auto-scheduled, they would run against prod.

**Comment by mhallwac** [comment]
Will the require_contentful_space method not apply when the tests are auto-scheduled?

**Comment by h-parekh** [comment]
Yes it will apply, Jenkins (auto-scheduler) can send default values.

**Comment by mhallwac** [comment]
So the default value will come from Jenkins or should I have the default value in read_contentful_tokens?

**Comment by h-parekh** [comment]
Great questions, making me rethink if we should set a default in read_contentful_tokens method.

I'm thinking if we require input value for USE_CONTENTFUL_SPACE then no point in setting a default. Which would be better because I want the tester to be sure of what contentful space they want to test against. Thoughts?

**Comment by mhallwac** [comment]
That's what I was thinking too.  Will Jenkins be able to give a value for USE_CONTENTFUL_SPACE?

**Comment by h-parekh** [comment]
Yes, it will be an input field no the job's form, and can send defaults when a user submits job without a value.

**Comment by mhallwac** [comment]
Perfect. I will finish the changes and get a PR in
