### ISSUE TITLE
visit '/' results in double slashes '//' when Capybara.app_host has trailing slashes

### ISSUE THREAD

**Issue by h-parekh** [ndlib/QA_tests#268]
### Descriptive summary
In `spec/curate/curate_config.yml` we have trailing slashes for each of the environment URLs.
When you run a test against any of these sites, `visit '/'` command appends an extra '/' to the call. 

### Rationale
This issue needs to be addressed for 2 reasons:
* It doesn't mimic actual user behavior, although it uncovered an interesting behavior on our site.
* [Assertions are failing ](https://github.com/ndlib/QA_tests/blob/master/spec/curate/pages/home_page.rb#L23)because `Capybara.app_host != current_url`

### Expected behavior
After `visit '/'` `current_url` should be equal to `https://curatepprd.library.nd.edu/`

### Actual behavior
After `visit '/'` `current_url`  is `https://curatepprd.library.nd.edu//`

### Steps to reproduce the issue

1. Add a debug statement `require 'byebug; debugger` before `visit '/'` in [curate specs scenario](https://github.com/ndlib/QA_tests/blob/master/spec/curate/functional/func_curate_spec.rb#L6) for `Load Homepage`

2. Run a test against curate pprd using this command:
```console
ENVIRONMENT=pprd SKIP_CLOUDWATCH=true bundle exec rspec spec/curate/functional/func_curate_spec.rb:5
```
3. Evaluate the values of `current_url` using byebug command line
```console
[2018-01-31 11:57:34.416] INFO  -- curate : test_type: functional	 runID: 2018-01-31T11:57:34.415-05:00	 context: "BEGIN example"	example: "User Browsing Load Homepage"	location: "./spec/curate/functional/func_curate_spec.rb:5"

[2, 11] in /Users/hparekh/git/QA_tests/spec/curate/functional/func_curate_spec.rb
    2: require 'curate/curate_spec_helper'
    3:
    4: feature 'User Browsing', js: true do
    5:   scenario 'Load Homepage', :read_only do
    6:     require 'byebug'; debugger
=>  7:     visit '/'
    8:     home_page = Curate::Pages::HomePage.new
    9:     expect(home_page).to be_on_page
   10:   end
   11:
(byebug) Capybara.app_host
"https://curatepprd.library.nd.edu/"
(byebug) visit '/'
[2018-01-31 11:57:42.009] INFO  -- curate : test_type: functional	 runID: 2018-01-31T11:57:34.415-05:00	 context: "visit"	path: "//"	host: "https://curatepprd.library.nd.edu/"
{"status"=>"success"}
(byebug) current_url
"https://curatepprd.library.nd.edu//"
```

### Analysis so far:
We recently [updated the version](https://github.com/ndlib/QA_tests/commit/b0370047cb237fa0d8b6caaa368f031babbda9ec#diff-e79a60dc6b85309ae70a6ea8261eaf95) of Capybara gem in our repository from 2.14.3 to 2.17.0

When I reverted the version back to 2.14.3, the issue doesn't happen. A [similar issue](https://github.com/teamcapybara/capybara/issues/1918) was reported in version 2.15.2 of capybara gem. But we should ensure that there isn't any monkey patching on our end before re-opening this with the capybara team.

**Comment by mhallwac** [comment]
Is this only happening for Curate?

**Comment by h-parekh** [comment]
If this is capybara related then it will be across the board, Curate is one that has a failing scenario hence a good candidate for troubleshooting. But it would be good to see how other specs are working as well.

**Comment by mhallwac** [comment]
I will troubleshoot Curate and then try another spec to see if it is happening across the board.

**Comment by h-parekh** [comment]
This issue has been addressed by https://github.com/ndlib/QA_tests/pull/269
