### ISSUE TITLE
Add support for reading 'tag objects' from swagger definitions

### ISSUE THREAD

**Issue by h-parekh** [ndlib/QA_tests#270]
### Descriptive summary
Currently, the QA framework does not know which operations need to be tested. So we are manually adding, removing and/or commenting operations we don't want to test. 
This enhancement request is to add support for reading metadata about each operation from the [tag object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#tag-object).

### Rationale
There could be many scenarios to use this tag, and this metadata will serve as a two-way communication between developers and testers:
- Dev team has merged an endpoint that isn’t ready for consumption
- Testing team has limitations to test that endpoint
- Testing for that endpoint isn’t necessary due to other test coverage

### Expected behavior
- Update the SwaggerHandler class to check if an operation has tag: 'skipTests' 
- If it does then skip testing that operation
- If it does not then continue with testing that operation
NOTE: Use monarchLibguides [spec](https://github.com/ndlib/QA_tests/tree/master/spec/monarchLibguides) for building this support. This is the only API for which we've [added tags](https://github.com/ndlib/monarch_libguides/blob/master/definitions/swagger.yml#L33)
- Make sure the other integration specs continue to work with this change

### Related work
[Google doc](https://docs.google.com/document/d/1ZLBFLNtqJNsR-8PDweAOq0qZOuTPhhUg7nicEg9w4aQ/edit) for bringing context from the original conversation

**Comment by mhallwac** [comment]
The tag is not under the operation but the operation.verb, correct?

**Comment by h-parekh** [comment]
Closed by https://github.com/ndlib/QA_tests/pull/274
