### ISSUE TITLE
Broken curate scenario for ORCIDHomePage

### ISSUE THREAD

**Issue by h-parekh** [ndlib/QA_tests#290]
### Descriptive summary
The '[Go to ORCID.org home page](https://github.com/ndlib/QA_tests/blob/master/spec/curate/functional/func_curate_spec.rb#L477)' scenario is failing when on the expectation for [OrcidHomePage](https://github.com/ndlib/QA_tests/blob/master/spec/curate/functional/func_curate_spec.rb#L494)

### Rationale
The 3 accounts (t_heslib01, t_heslib03 and t_heslib04) that are being used in this scenario are going to different pages when testing against curate pprd and curate prod.

In prod:
![screenshot_2018-03-21-10-58-46 446](https://user-images.githubusercontent.com/21689371/37729089-48a92902-2cf9-11e8-985c-972840f40fd6.png)

In pprd:
![screen shot 2018-03-21 at 10 55 55 am](https://user-images.githubusercontent.com/21689371/37729112-550e684c-2cf9-11e8-9d3c-37569effee3d.png)

### Expected behavior
Still need to be determined. Maybe we have 2 different scenarios here.

**Comment by h-parekh** [comment]
@mhallwac May be we should generalize the ['valid_page_content?' method](https://github.com/ndlib/QA_tests/blob/f12323e13953ad2825fce6a7df91648470d7f0bc/spec/curate/pages/orcid_home_page.rb#L23) to be able to assert for either of these pages.

**Comment by mhallwac** [comment]
It seems as though they are going to opposite pages, prod goes to sign in immediately while pprd goes to register account immediately.  Is this how they are each supposed to work?

**Comment by h-parekh** [comment]
If an account does not have an email ID registered in curate it is going to the 'Sign In' page, and if it does it is going to the 'Register account' page. Yes I think that's the way it should work. 

So it's working expected in both prod and pprd, the discrepancy being that t_heslib01,t_heslib03 and t_heslib05 have email fields blank in pprd and non_blank in prod. 

Do you agree?

**Comment by mhallwac** [comment]
what do you mean by email ID? the ORCID ID?

**Comment by h-parekh** [comment]
@mhallwac By email ID mean the one on curate account details page
<img width="779" alt="screen shot 2018-03-21 at 1 03 53 pm" src="https://user-images.githubusercontent.com/21689371/37736022-faf2f6f2-2d0c-11e8-9fee-107c4390f788.png">

On further testing, I found that the current specs pass in pprd and only fail in prod. There are some internmittent failures in pprd when the orcid.org page doesn't load fully. I'm going to work on prod data setup from server side and remove email ID registrations for t01, t03 and t05 accounts to confirm this behavior further. If that works then we won't need to make any spec changes.

**Comment by h-parekh** [comment]
In curate pprd and prod, the curate profiles for t_heslib01, t_heslib03, and t_heslib04 do not have a registered email. So they should all go to the sign in page. 

Lets update the scenario name from 'Go to ORCID.org home page' to 'Go to ORCID.org sign in page', and update the assertions in ['valid_page_content?' method](https://github.com/ndlib/QA_tests/blob/f12323e13953ad2825fce6a7df91648470d7f0bc/spec/curate/pages/orcid_home_page.rb#L23) to look for elements on the sign in page: https://orcid.org/signin

**Comment by mhallwac** [comment]
Got it. So 'valid_page_content' should account for the two different pages based on the AccountDetailsUpdated field for the the test users?

**Comment by h-parekh** [comment]
Addressed by: https://github.com/ndlib/QA_tests/pull/292
